name: BitBucket Mirror

on:
  push:
    branches: [ "**" ]

jobs:
  bitbucket_mirror:
    runs-on: ubuntu-latest

    steps:
    # Download a mirror and push it to GitLab
    - run: |
        git clone --mirror https://github.com/rust-multiplatform/Base-Project-Template mirror_repo
        cd mirror_repo
        git push --mirror https://sakul6499:$BITBUCKET_TOKEN@bitbucket.org/rust-multiplatform/base-project-template.git
      env:
        BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
