name: Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Cache target/
        id: target-cache
        uses: actions/cache@v3
        with:
          path: target
          key: shared-${{ runner.os }}-target

      - name: Cache Cargo-Home (compiled/installed binaries)
        id: cargo-coverage-home
        uses: actions/cache@v3
        with:
          path: /home/runner/.cargo
          key: cargo-coverage-home

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Setup nightly toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      # Clean workspace
      - uses: actions-rs/cargo@v1
        with:
          command: clean

      # Run tests
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --no-fail-fast # Customize args for your own needs
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"
          RUSTDOCFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests"

      # Setup stable toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Run grcov
      - id: coverage
        uses: actions-rs/grcov@v0.1

      # Codecov.io upload
      - uses: codecov/codecov-action@v4
