name: Platform macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  platform_macos:
    strategy:
      matrix:
        os: [macos-latest]
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile minimal -y

    - name: Install target ${{ matrix.target }}
      run: rustup target add ${{ matrix.target }}

    - name: Check
      run: cargo check --verbose --package platform_macos
    - name: Build (Debug)
      run: cargo build --verbose --package platform_macos
    - name: Build (Release)
      run: cargo build --verbose --package platform_macos --release
    - name: Run Tests (Debug)
      if: ${{ matrix.target == 'x86_64-apple-darwin' }} # Testing can only be done on the host architecture. It should work across all architectures though!
      run: cargo test --verbose --package platform_macos
    - name: Run Tests (Release)
      if: ${{ matrix.target == 'x86_64-apple-darwin' }} # Testing can only be done on the host architecture. It should work across all architectures though!
      run: cargo test --verbose --package platform_macos --release

    - name: List target/ Files
      run: ls -al target/*

    - uses: actions/upload-artifact@v3
      with:
        name: platform_macos
        path: target/
