[package]
name = "platform_linux"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-multiplatform/Base-Project-Template.git"

[dependencies]
shared = { path = "../../shared" }
